# -*- coding: utf-8 -*-
"""data_mining_case_study_notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cyVaEkkwdY54T4R6VM_OnTbmY0qKbvP_
"""

!pip install mlxtend --quiet

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

file_url = "https://drive.google.com/file/d/1JYix38cDVVd_NJZnp7sz8NWLYsogLSGi/view?usp=sharing"

download_url = f"https://drive.google.com/uc?export=download&id={file_id}"

import pandas as pd

df = pd.read_csv(download_url)
df.head()

df_ap = df[[
    "vehicle_type",
    "payment_type",
    "weather",
    "time_of_day",
    "surge_multiplier",
    "is_cancelled",
    "high_fare"
]]

df_ap = df_ap.astype(str)

transactions = df_ap.values.tolist()

te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df_trans = pd.DataFrame(te_ary, columns=te.columns_)

df_trans.head()

frequent_itemsets = apriori(
    df_trans,
    min_support=0.05,
    use_colnames=True
)

frequent_itemsets.sort_values("support", ascending=False).head(10)

rules = association_rules(
    frequent_itemsets,
    metric="lift",
    min_threshold=1
)

rules.sort_values("lift", ascending=False).head(10)

# Top 10 Frequent Itemsets
top_items = frequent_itemsets.sort_values("support", ascending=False).head(10)

plt.figure(figsize=(10,6))
sns.barplot(x=top_items["support"], y=top_items["itemsets"].astype(str))
plt.title("Top 10 Frequent Itemsets")
plt.xlabel("Support")
plt.ylabel("Itemsets")
plt.show()

#Confience V/S Lift

plt.figure(figsize=(8,5))
plt.scatter(rules['confidence'], rules['lift'], alpha=0.6)
plt.xlabel("Confidence")
plt.ylabel("Lift")
plt.title("Confidence vs Lift")
plt.grid(True)
plt.show()

#Support Distribution Plot

plt.figure(figsize=(8,5))
plt.hist(frequent_itemsets["support"], bins=20, edgecolor='black')
plt.title("Distribution of Support Values")
plt.xlabel("Support")
plt.ylabel("Frequency")
plt.show()

# Bubble Plot
plt.figure(figsize=(8,5))
plt.scatter(
    rules['support'],
    rules['confidence'],
    s=rules['lift'] * 50,   # bubble size
    alpha=0.5
)
plt.xlabel("Support")
plt.ylabel("Confidence")
plt.title("Support vs Confidence (Bubble Size = Lift)")
plt.grid(True)
plt.show()

